### ISSUE TITLE
listing all error "KeyError: 'hash'"

### ISSUE THREAD

**Issue by jpage4500** [twistedfall/utorrentctl#7]
I'm getting this error when listing all on both a Mac OSX and Windows running the latest. Both have Python 3.5.1 installed as well.

```
~/Documents/GoogleDrive/Configuration/uTorrent$ python3 utorrentctl/utorrentctl.py -ssl -l
Traceback (most recent call last):
  File "utorrentctl/utorrentctl.py", line 213, in <module>
    print_console( t.verbose_str( opts.format ) )
  File "/Users/username/Documents/GoogleDrive/Configuration/uTorrent/utorrentctl/utorrent/torrent.py", line 108, in verbose_str
    return self._format_to_str( self._process_format( self._default_format if format_string is None else format_string ) )
  File "/Users/username/Documents/GoogleDrive/Configuration/uTorrent/utorrentctl/utorrent/torrent.py", line 94, in _process_format
    val = formatter.get_field( field_name if def_field_name is None else def_field_name, None, args )[0]
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/string.py", line 296, in get_field
    obj = self.get_value(first, args, kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/string.py", line 253, in get_value
    return kwargs[key]
KeyError: 'hash'
```

NOTE: I can get this command to work when adding the "-n" option so it's not a configuration issue.
```
python3 utorrentctl/utorrentctl.py -ssl -l -n
```

**Comment by jpage4500** [comment]
turns out the issue was just using the wrong variable name for hash code.. I replaced the following 2 {hash} entries with {hash_code} and all's well:
```
[utorrent/torrent.py]
	_default_format = "{hash_code} {status} {progress}% {size} {dl_speed} {ul_speed} {ratio} {peer_info} eta: {eta} {name} {label}"

[config.py]
	"default_torrent_format" : "{hash_code} {status} {progress}% {size} {dl_speed} {ul_speed} {ratio} {peer_info} eta: {eta} {name} {label}",

```
